In [3]:
import numpy as np
rng = np.random.default_rng(seed=1701) # seed for reproducibility
x1 = rng.integers(10, size = 6) #one dimensional array
x2 = rng.integers(10,size=(3,4)) # two dimensional array
x3 = rng.integers(10,size=(3,4,5)) # Three dimensional array

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


In [5]:
x1

array([9, 4, 0, 3, 8, 6], dtype=int64)

In [6]:
x1[0]

9

In [7]:
x1[4]

8

In [8]:
x1[-1]

6

In [9]:
x1[-2
]

8

In [10]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [11]:
x2[0,0]

3

In [12]:
x2[2,0]

0

In [13]:
x2[2,-1]

9

In [14]:
x2[0,0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [15]:
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [16]:
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)