In [1]:
import numpy as np

In [3]:
a = np.array([0 ,1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [4]:
a + 5


array([5, 6, 7])

In [6]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [9]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [10]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])