In [1]:
from myscript import square

1 squared is 1
2 squared is 4
3 squared is 9
4 squared is 16
5 squared is 25
6 squared is 36
7 squared is 49
8 squared is 64
9 squared is 81


In [50]:
square(5)


25

In [51]:
import math

In [52]:
math.sin(2)

0.9092974268256817

In [7]:
L = list(range(10))
L 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(L[0])

int

In [9]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
 import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
import numpy as np


In [15]:
# Integer array
np.array([1,4,2,5,3])


array([1, 4, 2, 5, 3])

In [16]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [17]:
np.array([1,2,3,4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [19]:
# Create a length-10 integer array filled with 0s
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# Create a 3 x 5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
# Create an array with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built in range function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
# Create a 3x3 array of uniformly distributed 
# Pseudorandom values between 0 and 1
np.random.random((3,3))

array([[0.25809089, 0.48079074, 0.97972095],
       [0.29361778, 0.89811023, 0.17318836],
       [0.96355358, 0.39464492, 0.19817359]])

In [25]:
# Create 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.99146129,  0.65739957,  1.06696206],
       [-0.605463  ,  0.67689519,  0.83794382],
       [ 0.25522352, -1.15769743,  1.09683671]])

In [26]:
# Create a 3x3 array of pseudorandom integers in the interval [0,10)
np.random.randint(0,10,(3,3))

array([[2, 9, 8],
       [8, 2, 4],
       [5, 4, 4]])

In [27]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Create an uninitialized array of three integers; the values will be
# whatever happens to already exist at that memory location
np.empty(3)

array([0.e+000, 5.e-324, 1.e-323])