In [2]:
import numpy as np
import math

In [3]:
a = np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [4]:
# If we pass in a list of lists in a numpy array, we create a multi-dimensional array, for instance, a matrix

b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.shape

(2, 3)

In [6]:
a.dtype


dtype('int32')

In [7]:
c = np.array([2.2,5. ,1.1])
c.dtype.name

'float64'

In [8]:
c

array([2.2, 5. , 1.1])

In [9]:
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
np.random.rand(2,3)

array([[0.69378032, 0.38389407, 0.97608163],
       [0.38408579, 0.29084356, 0.43090618]])

In [11]:
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [12]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [13]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

# Lets look at a -b
c = a -b 
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [14]:
# Real world problem

farenheit = np.array([0,-10,-5,-15,0])

celcius = (farenheit-31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [15]:
# Boolean array to check
celcius > -20

array([ True, False, False, False,  True])

In [16]:
celcius%2 == 0

array([False, False,  True, False, False])

A

In [17]:
# Besides element wise manipulation, it is important to know that numpy supports matrix manipulation
# look at matrix product, if we want to do element wise product, we use the * sign

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B)

# If we want to do matrix product, we use the @ sign or use the dot function
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [18]:
A.shape

(2, 2)

In [19]:
array1 = np.array([[1,2,3],[4,5,6]])
print(array1.dtype)

array2 = np.array([[7.1,8.2,9.1],[10.4,11.2,12.3]])
print(array2.dtype)

int32
float64


In [20]:
array3 = array1 + array2
print(array3)
print(array3.dtype)

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [21]:
print(array3.sum())
print(array3.max())   
print(array3.min())
print(array3.mean())

79.3
18.3
8.1
13.216666666666667


In [22]:
# Create an array with 15 elements, ranging from 1 to 15
# with a dimension of 3x5

b = np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [24]:
# Indexing Slicing and iterating
a = np.array([1,3,5,7])
a[2]

5

In [25]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a[1,1]

4

In [27]:
a[0,0]

1

In [29]:
np.array([a[0,0],a[1,1],a[2,1]])


array([1, 4, 6])

In [30]:
print(a>5)

[[False False]
 [False False]
 [False  True]]


In [31]:
print(a[a>5])

[6]


In [32]:
# Slicing
a = np.array([0,1,2,3,4,5])
print(a[:3])

[0 1 2]


In [33]:
print(a[2:4])

[2 3]
